version: '3.8'

services:
  mysql:  # Nombre del servicio
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: frases_sql
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Archivo de inicialización
      - db_data:/var/lib/mysql  # Volumen persistente para los datos
    ports:
      - "3307:3306"

volumes:
  db_data:  # Declaración del volumen para persistencia